# Generated by Django 5.2.8 on 2025-12-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='additional_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='institution_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
