# Generated by Django 5.2.8 on 2025-12-12 17:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text="Unique id for a model's object", primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Is the model's object active")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text="Creation date of the model's object")),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text="Updating date of the model's object")),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='clubs/events/')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_link', models.URLField(blank=True, null=True)),
                ('event_audience', models.CharField(blank=True, choices=[('CLUB_MEMBERS', 'club_members'), ('UNIVERSITY', 'university'), ('PUBLIC', 'public'), ('PRIVATE', 'private')], max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('ONGOING', 'ongoing'), ('UPCOMING', 'upcoming'), ('COMPLETED', 'completed')], max_length=50, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_event', to='club.club')),
            ],
            options={
                'db_table': 'event',
                'ordering': ['-created_at'],
            },
        ),
    ]
