# Generated by Django 5.2.8 on 2025-12-12 17:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text="Unique id for a model's object", primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Is the model's object active")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text="Creation date of the model's object")),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text="Updating date of the model's object")),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='university/')),
                ('email_domain', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'university',
                'ordering': ['-created_at'],
            },
        ),
    ]
