# Generated by Django 5.2.8 on 2025-12-12 17:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text="Unique id for a model's object", primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Is the model's object active")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text="Creation date of the model's object")),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text="Updating date of the model's object")),
                ('club_position', models.CharField(blank=True, choices=[('PROBATIONARY_MEMBER', 'probationary_member'), ('GENERAL_MEMBER', 'general_member'), ('SENIOR_MEMBER', 'senior_member'), ('SUB_EXECUTIVE_BODY', 'sub_executive_body'), ('EXECUTIVE_BODY', 'executive_body')], max_length=50, null=True)),
                ('additional_club_position', models.CharField(blank=True, choices=[('PRESIDENT', 'president'), ('VICE_PRESIDENT', 'vice_president'), ('TREASURER', 'treasurer'), ('JOINT_SECRETARY', 'joint_secretary'), ('GENERAL_SECRETARY', 'general_secretary')], max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('CURRENT', 'current'), ('FORMER', 'former'), ('REJECTED', 'rejected'), ('PENDING', 'pending')], max_length=50, null=True)),
                ('recruitment_semester', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_membership', to='club.club')),
            ],
            options={
                'db_table': 'membership',
                'ordering': ['-created_at'],
            },
        ),
    ]
